#!/bin/bash

if [ $# -lt 2 ]; then
   echo "Insufficient number of arguements" >&2   
   exit 1
fi

if [ -a "$1" ]; then
   echo "Error: first file exists" >&2
   exit 1
fi

out="$1"

shift

cat "$@" 2> "$out"	#redirects stderror to output file

exit 0
